server:
  servlet:
    context-path: /bookshopAdmin
  port: 9090

spring:
  datasource: # MySQL 配置
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL驱动，无需修改
    url: jdbc:mysql:///bookshop07?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root # 数据库连接名
    password: 123456 # 数据库连接密码
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 192.168.124.13
    username: yan
    password: 123456
  elasticsearch:
    rest:
      uris: 192.168.124.13:9200
      connection-timeout: 100000
      read-timeout: 50000  

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml    #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  configuration:
    call-setters-on-nulls: true
  global-config:
    banner: false
    db-config:
      select-strategy: not-empty
    
shiro:
  unauthorizedUrl: /403.html
  loginUrl: /login.html
  successUrl: /admin/index.html
  
logging: # 配置日志
  pattern:   # 配置日志格式
    console: level - %p - %m%n
  level:
    root: warn   # 指定Spring Boot启动日志级别
